{% set name = "xnat" %}
{% set version = "0.3.26" %}
{% set sha256 = "56a2291b12fb8a007a6cbea0465eb065763ec0380bbe9f1490e574d7408ce562" %}


package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - xnat_cp_project = xnat.scripts.copy_project:main


requirements:
  build:
    - python
    - pip

  run:
    - python
    - sphinx_rtd_theme >=0.1.9
    - progressbar2 >=3.11.0
    - isodate >=0.5.4
    - requests >=2.10.0
    - six >=1.13.0


test:
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest --junitxml=junit-{envname}.xml --cov=xnat --cov-report=xml:coverage-{envname}.xml --cov-report=html:cov-html-{envname} --cov-report=term


about:
  home: https://gitlab.com/radiology/infrastructure/xnatpy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A new XNAT client that exposes XNAT objects/functions as python objects/functions.
  doc_url: https://xnat.readthedocs.io/
  dev_url: https://gitlab.com/radiology/infrastructure/xnatpy

extra:
  recipe-maintainers:
    - pauldmccarthy
