{% set name = "xnat" %}
{% set version = "0.6.2" %}
{% set sha256 = "0d580323a267e8c70f7d2d961830be4c3874e82429e3a93871df5c923acbb6c8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - xnat_cp_project           = xnat.scripts.copy_project:main
    - xnat_data_integrity-check = xnat.scripts.data_integrity_check:main
    - xnat                      = xnat.cli:cli


requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - click >=8
    - click-option-group >=0.5.6
    - importlib-metadata >=8.5.0
    - isodate >=0.6
    - progressbar2 >=4.2
    - pydicom >=3.0.1
    - python-dateutil >=2.9.0
    - pyyaml >=6
    - requests >=2.30


# The pypi source package does not contain
# unit tests, so we can't run them through
# conda build (last checked v0.4.0).
test:
  imports:
    - xnat
    - xnat.cli
    - xnat.cli.download
    - xnat.cli.helpers
    - xnat.cli.importing
    - xnat.cli.listings
    - xnat.cli.prearchive
    - xnat.cli.rest
    - xnat.cli.scripts
    - xnat.cli.search
    - xnat.constants
    - xnat.convert_xsd
    - xnat.core
    - xnat.datatypes
    - xnat.exceptions
    - xnat.header
    - xnat.inspect
    - xnat.map
    - xnat.mixin
    - xnat.plugins
    - xnat.prearchive
    - xnat.search
    - xnat.services
    - xnat.session
    - xnat.type_hints
    - xnat.users
    - xnat.utils
  commands:
    - pip check
    - xnat --help
  requires:
    - pip

about:
  home: https://gitlab.com/radiology/infrastructure/xnatpy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A new XNAT client that exposes XNAT objects/functions as python objects/functions.
  doc_url: https://xnat.readthedocs.io/
  dev_url: https://gitlab.com/radiology/infrastructure/xnatpy

extra:
  recipe-maintainers:
    - pauldmccarthy
