{% set name = "xnat" %}
{% set version = "0.3.25" %}
{% set sha256 = "37b30a98a72fe4c7e636cd6a433da9fd6edfd7dee109f185849c78e9dc54effd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - xnat_cp_project = xnat.scripts.copy_project:main


requirements:
  build:
    - python
    - pip

  run:
    - python
    - sphinx_rtd_theme >=0.1.9
    - progressbar2 >=3.11.0
    - isodate >=0.5.4
    - requests >=2.10.0
    - six >=1.13.0

test:
  imports:
    - xnat
    - xnat.constants
    - xnat.convert_xsd
    - xnat.core
    - xnat.datatypes
    - xnat.exceptions
    - xnat.inspect
    - xnat.mixin
    - xnat.prearchive
    - xnat.search
    - xnat.services
    - xnat.session
    - xnat.users
    - xnat.utils

about:
  home: https://gitlab.com/radiology/infrastructure/xnatpy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A new XNAT client that exposes XNAT objects/functions as python objects/functions.
  doc_url: https://xnat.readthedocs.io/
  dev_url: https://gitlab.com/radiology/infrastructure/xnatpy

extra:
  recipe-maintainers:
    - pauldmccarthy
