{% set name = "xnat" %}
{% set version = "0.3.10" %}
{% set sha256 = "c12a746a76b0c4e86bf21a58c38ff051d87a9cd4add7d352e18238b020aa3888" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - sphinx_rtd_theme >=0.1.9
    - progressbar2 >=3.11.0
    - isodate >=0.5.4
    - requests >=2.10.0
    - six >=1.9.0


test:
  commands:
    - python -c "import xnat"

about:
  home: https://bitbucket.org/bigr_erasmusmc/xnatpy/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A new XNAT client that exposes XNAT objects/functions as python objects/functions.'
  doc_url: http://xnat.readthedocs.io/
  dev_url: https://bitbucket.org/bigr_erasmusmc/xnatpy/

extra:
  recipe-maintainers:
    - pauldmccarthy
