{% set name = "xnat" %}
{% set version = "0.6.0" %}
{% set sha256 = "934ff97636ba74106f696ba3a3d724a087736fc3a49a19148d41503a2fa90a26" %}


package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - xnat_cp_project           = xnat.scripts.copy_project:main
    - xnat_data_integrity-check = xnat.scripts.data_integrity_check:main
    - xnat                      = xnat.client:cli


requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - progressbar2 >=3.11.0
    - importlib_metadata >=6.8.0
    - isodate >=0.5.4
    - requests >=2.10.0
    - click >=7.0.0
    - pydicom >=2.3.0
    - python-dateutil =2


# The pypi source package does not contain
# unit tests, so we can't run them through
# conda build (last checked v0.4.0).
test:
  imports:
    - xnat
    - xnat.client
    - xnat.constants
    - xnat.convert_xsd
    - xnat.core
    - xnat.datatypes
    - xnat.exceptions
    - xnat.inspect
    - xnat.mixin
    - xnat.prearchive
    - xnat.search
    - xnat.services
    - xnat.session
    - xnat.users
    - xnat.utils


about:
  home: https://gitlab.com/radiology/infrastructure/xnatpy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A new XNAT client that exposes XNAT objects/functions as python objects/functions.
  doc_url: https://xnat.readthedocs.io/
  dev_url: https://gitlab.com/radiology/infrastructure/xnatpy

extra:
  recipe-maintainers:
    - pauldmccarthy
