{% set name = "xnat" %}
{% set version = "0.3.12" %}
{% set sha256 = "f9ef18449eb52849e45b21ab4c03e64a8cc3282ba276d7b09409ad254e0d64e7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - xnat_cp_project = xnat.scripts.copy_project:main


requirements:
  build:
    - python >=2.7,<=3.6
    - pip

  run:
    - python >=2.7.*,<=3.6.*
    - sphinx_rtd_theme >=0.1.9
    - progressbar2 >=3.11.0
    - isodate >=0.5.4
    - requests >=2.10.0
    - six >=1.9.0

test:
  imports:
    - xnat
    - xnat.constants
    - xnat.convert_xsd
    - xnat.core
    - xnat.datatypes
    - xnat.exceptions
    - xnat.inspect
    - xnat.prearchive
    - xnat.search
    - xnat.services
    - xnat.session
    - xnat.users
    - xnat.utils
    - xnat.xnatbases

about:
  home: https://bitbucket.org/bigr_erasmusmc/xnatpy/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A new XNAT client that exposes XNAT objects/functions as python objects/functions.'
  doc_url: http://xnat.readthedocs.io/
  dev_url: https://bitbucket.org/bigr_erasmusmc/xnatpy/

extra:
  recipe-maintainers:
    - pauldmccarthy
