travis:
  secure:
    BINSTAR_TOKEN: hfHUQxBfLWT4zJ6PCYWzjUv09+ViDM1J/JRKzVrbzuUZF5dLBJW+S0TRvhjNP8M3wJ1tMdcfr7rDh/AweyXPtTdwoqUMoujmLBLhTdqrrXlQ1a68uaO9cLbWkAvqZS8UrApiNRaXUCpwsxdV/SqPQqfOu9+VBC/h75Emck/YdzI+lZpFUwtgrHQaxNxG609/ZGkAA05ILFcCRz3eq9XXIc7zSAGx/kPGZs0XPPwQ7bwAlWttk+F1zPmyvUMuPidFau93qX+ZMwz2GFMas/Lk+9UhO1Z3HgwSFkK1yxDO4SqlbEC8GRfxS9r87GaJg4TbXPAmUe5fFWF67LY5ijcvjAAHah0FDNcJ6MBH9TnzB5+Yta9ijy5b2T0jVKa9VKxSqsHy4pBKel4+VYqdWuSCgGocxZNMNqUziTY1KMaXolhr73TdxdDbDuAcLq8wZKfCNHSTv4JofD18WNttWU2V6GzLOzIO7cJnWpdqKMlBPrIDDlxDKIKa2S9X/kwXwc2BtDKT6vXB6nMLVEW5QrbBJTQ1k+g/p7rHOpv0zhUl0PYQn8ztd61bRcLqgqF7xeeiDgJ8sXs/Ed6LGi5hElwZ1osEV6eOWjWrTkxYfmjh16k+mFNeMh6LsYEMH7Hghcew2tN4r1pKQml1i5fLbuhiRijdVEZOGGyFSszQY35wu8M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
