travis:
  secure:
    BINSTAR_TOKEN: H5YfT41exB0mtYmSV/YvcLzIvkmIGZVPVKZKSX8JPzQJ4tOgLpVdJDox2GxXa8Y/wxkzJ3VeuSQXadv9RqAgoxmh1BL9RPf6NYG6KSHGJEw9fJ9b8IxrKj7RR/gHALLRGfPqCpXVGaIGdeap1hPj0F8CpzTdGiowrGOtbhjoik6MwiwdtHZOWliqZeWbFTgaCdpGBSsnp7HVkzCD5r458WjWg0ZbtkTj/Iw1aKW6JpVPxFo8GBTZQcjXaQbtWH5gcZj36x5wncOmpxSfqvceqfoM3fO+lSnwbA0AhH9b3jDyHh0ciSN8PKCeEWojUupfRGefzfa1O4zbevn8BZarF6krShujUYLmv1FPCQyXKZM/qC2o5a1aLVpHtvpSetAYqF2jSmMBM9i69Zr4wy/j3W/e7uvDLDPav1yB1E3JcAd2xiUfVdxORH6Uzi97SUOnKgGvOI3SDLP0gw1lkK8o3UYXhxMxhlM3mMa7fNuZTbCbMoSveOc3Eythz3OFOLDagYlvmac8mKkJrbryq+IVe1bDUy0Unm8GUVKWQrLelAWBYppogRO9i/4D6jechm3dKpHxV/lZxHlV1xD+6w/iv+WG3lAtjlyQ+KymVReUgDOQ99pe/G5tBZe5GQo09NOK+/3wmTYNjFJ+00LpyM5K33maz9OsK8HbmcUIHVPrlI0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
